server:
  port: 1994
jobs:
  cron1: 0/5 * * * * ?
  cron2: 0/1 * * * * ?
spring:
  datasource:
    url: jdbc:mysql://47.99.106.85:3306/allenpeng?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name:  com.mysql.cj.jdbc.Driver
logging:
  level:
    com.demo.mapper: TRACE